# Generated by Django 6.0 on 2025-12-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('incomeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=11)),
                ('other', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Outgoings',
            fields=[
                ('outID', models.BigAutoField(primary_key=True, serialize=False)),
                ('accom', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Accommodation')),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=11)),
                ('travel', models.DecimalField(decimal_places=2, max_digits=11)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=11)),
                ('entertainment', models.DecimalField(decimal_places=2, max_digits=11)),
                ('other', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
